---
title: "some notes on sequence analysis"
author: "Christof Neumann"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{some notes on sequence analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(cfp)
```

# slope of elements

```{r, echo=FALSE, fig.height=3.5, fig.cap="\\label{fig:slopelements}Two example sequences and the slope of the occurence of A in response to position in the sequence. In the left panel the slope is steeper because A is much more likely to occur at the beginning than at the end. In the right panel, the slope is flatter, i.e. A might occur both at the beginning and at the end of the sequence."}
par(mfrow=c(1, 2))
S <- c("AAABBAABBBBB")
S <- unlist(strsplit(S, ""))
x <- data.frame(pos=1:length(S), isA=as.numeric(S=="A"))
plot(x$pos, x$isA, pch=S, xlab="position", ylab="prob of A occured", xlim=c(1,12), cex.axis=0.7, cex.lab=0.7, cex=0.7)
mod <- lm(isA ~ pos, x)
points(x$pos, predict(mod), "l", col="red", lwd=2)
mod <- glm(isA ~ pos, x, family = binomial)
points(x$pos, predict(mod, type="response"), "l", col="blue", lwd=2, lty=3)
legend(x = 1, y = 0.4, lty=c(1,3), col=c("red", "blue"), legend=c("linear", "logistic"), cex=0.5)

S <- c("AAABBAA")
S <- unlist(strsplit(S, ""))
x <- data.frame(pos=1:length(S), isA=as.numeric(S=="A"))
plot(x$pos, x$isA, pch=S, xlab="position", ylab="prob of A occured", xlim=c(1,12), cex.axis=0.7, cex.lab=0.7, cex=0.7)
mod <- lm(isA ~ pos, x)
points(x$pos, predict(mod), "l", col="red", lwd=2)
mod <- glm(isA ~ pos, x, family = binomial)
points(x$pos, predict(mod, type="response"), "l", col="blue", lwd=2, lty=3)
#legend("bottomleft", lty=c(1,3), col=c("red", "blue"), legend=c("linear", "logistic"), cex=0.5)
legend(x = 1, y = 0.4, lty=c(1,3), col=c("red", "blue"), legend=c("linear", "logistic"), cex=0.5)
```



